### ISSUE TITLE
Add cover sheet or appendix w/source & metadata info

### ISSUE THREAD

**Issue by gsarfaty** [USAID-ICPI/OHA-Tableau-Dashboard-QA-QC#1]
Add Tab to insert link to [R code](https://github.com/noahbartlett/Me_One_Last_Kiss/issues), document source data, any known issues, contact info, etc.

**Comment by kschlenker** [comment]
Let's be sure that this includes a note that Namibia's data is still from the Q2 initial data entry period, not the Q2 cleaning period

**Comment by jrose202** [comment]
can we note that all HTS positivity calculations in this workbook are HTS POS/HTS POS + NEG.  HTS TST does not always equal POS + NEG 

this is consistent with Pano but bears repeating.

**Comment by noahbartlett** [comment]
This should be where we include the "View by mechanism or partner" option.
