### ISSUE TITLE
PMTCT Tabs

### ISSUE THREAD

**Issue by nmcdavid** [USAID-ICPI/OHA-Tableau-Dashboard-QA-QC#11]
Noticed that the newly identified and yield tabs are no longer available. Not sure if that was intentional or not. Wanted to take note.

**Comment by noahbartlett** [comment]
This was intentional for this version. They were posing unexpected problems with the age disaggs, so in order to get speed out the dashboards on Tuesday, I had to eliminate those two tabs. We can re-incorporate when we have time to think them through.
