### ISSUE TITLE
Decimal place

### ISSUE THREAD

**Issue by achafetz** [USAID-ICPI/OHA-Tableau-Dashboard-QA-QC#12]
Can we remove the decimal place? Adds clutter and give sense of false precision 

![image](https://user-images.githubusercontent.com/8933069/42333598-28e52938-8049-11e8-94ba-76d508445963.png)

**Comment by noahbartlett** [comment]
This can be done. 
Should it be done? I would like group consensus on this. 
I will switch it to no decimal for now, but want others to weigh in.

**Comment by jrose202** [comment]
I'm agnostic (atheist?)


**********************
*JESSICA ROSE*
Sr. Technical Advisor, SIEI/SI Team | Office of HIV/AIDS
U.S. AGENCY FOR INTERNATIONAL DEVELOPMENT
T: 571.551.7524  | M: 571.225.6652 | jrose@usaid.gov  |  USAID.gov  |
 @USAID
