### ISSUE TITLE
Volume Positivity scatterplot

### ISSUE THREAD

**Issue by jrose202** [USAID-ICPI/OHA-Tableau-Dashboard-QA-QC#14]
Outstanding issues:
none

checked thoroughly Mozambique
checked birefly Angola, ARP, Botswana, Nigeria, Rwanda

note that HTS POS + NEG often don't match HTS TST

**Comment by noahbartlett** [comment]
As you and I discussed, this is a feature not a bug. We can collectively decide if we want to label the "total number tested" in that graph with Total_Numerator (to be consistent with Pano) or HTS_POS + HTS_NEG (to be consistent with the yield calculation).

**Comment by jrose202** [comment]
Pano uses POS + NEG - so we are consistent.  recommend a reminder on the cover page that this is how positivity is calculated.
