### ISSUE TITLE
OU.07: Age/Sex Results Tab Issues

### ISSUE THREAD

**Issue by jacobbuehler** [USAID-ICPI/OHA-Tableau-Dashboard-QA-QC#19]
*** There are too many indicators/disaggs to review, so I am doing each problem identified as an issue, please know if this is incorrect ***

Outstanding issues:

* OVC Totals

**Comment by jacobbuehler** [comment]
**HERE ARE THE PANO TOTALS FOR TZ:**
![fy18 tz_ovc_serv - semifine - pano](https://user-images.githubusercontent.com/7526089/42339676-ac13da9a-805b-11e8-9392-93a89d9405c7.PNG)

**HERE IS THE TABLEAU CROSSTAB (note inconsistent data):**
![fy18 tz_ovc_serv - semifine - tableau](https://user-images.githubusercontent.com/7526089/42339675-ac01ab72-805b-11e8-8dec-2b3cdf386947.PNG)

**THIS IS WHAT THE DATIM DATASET REPORT SHOWS:**
![fy18 tz_ovc_serv - datim dataset report](https://user-images.githubusercontent.com/7526089/42339674-abebe404-805b-11e8-93ce-c3af430ee87a.PNG)

As far as I can tell, we are pulling incorrect values for our age/sex disaggs for OVC_SERV--should be just the sum of the age/sex disaggs as shown in DATIM and reflected in Pano.

**Comment by noahbartlett** [comment]
Nice pick-up. It was an issue with a little-used disag for OVC_SERV (age/sex/service). Fixed for OVC_SERV. They now match with Pano. 

If there are other indicators which are having similar issues, flag them. It is likely an issue of which disaggregates are being used.

**Comment by jacobbuehler** [comment]
Having trouble getting Pano and tableau to match for PMTCT_STAT; will provide some screenshots here. Unclear what the issue is, other than the fact that the semifine to fine migration was not a smooth one (i.e., missing data in "fine" looking across Q1 + Q2).  

[Link to PMTCT_STAT comparison screenshots](https://drive.google.com/open?id=1GUh5YqxAb0n75NWqjQ0Phshn3NDpNyNw)

Jessica, let's look at this one together...

**Comment by jacobbuehler** [comment]
For VMMC_CIRC, Semi-Fine is correct, but Fine is hard to interpret because Pano does not carry forward the Semi-Fine age disaggs from Q1 (meaning that it is very difficult to interpret/compare Pano "Fine" to Tableau "Fine" since we are keeping in all the relevant age disaggs from Q1 that pre-date the "fine" launch. Not a show-stopper, but we should probably add language on our Instructions page to this effect:

_In cases where partners reported "Semi-Fine" results in Q1 and "Fine" results in Q2, this report attempts to consolidate cumulative FY reporting to maximize completeness in the "Fine" age grouping. However, this may lead to inconsistencies between this report and the Panorama "Age and Sex Disaggregates" Dashboard. Please exercise caution when summarizing age band totals, and be sure to cross-check your work in DATIM or Panorama to verify these age breakdowns._
