### ISSUE TITLE
Global O4

### ISSUE THREAD

**Issue by kgichuhi** [USAID-ICPI/OHA-Tableau-Dashboard-QA-QC#20]
**Global 04**
**_QA/QC_**

- Exported Crosstab to Excel for HTS_TST_POS and all data points matched
- Unable to compare to Panorama since Panorama does not provide global summary data

**_Recommended Changes_**

1. Would like to add an OU filter

**Comment by noahbartlett** [comment]
This tab was designed to be a global overview. There are other tabs which look at OU-specific proportion of results by agency.

**Comment by noahbartlett** [comment]
Added OU filter to this tab.
