### ISSUE TITLE
HTS 03 tab: HTS_POS numbers in fine age bands (potential issue)

### ISSUE THREAD

**Issue by AnnaBuschur** [USAID-ICPI/OHA-Tableau-Dashboard-QA-QC#22]
Focused on Angola data. Please see details below, including one potential issue:

- Semi-fine: No unknown age band, affecting totals for HTS_NEG
- Most complete coarse: no issues
- **Fine: Age band totals do not match for 6 different age groups in HTS_POS. This leads to a 25% difference between Tableau an Panorama totals for Angola. [Details here](https://drive.google.com/file/d/1qGyge-qzQKQIDz_-ZaSHTVsPhz9FSFdO/view?usp=sharing) (FY18 data)**

**Comment by noahbartlett** [comment]
The Pano numbers are only for Q2, which explains the discrepency. 

This is an issue across the board with fine age disags which we will have to collectively decide how to resolve. Pano only counts fine age disaggs starting in FY18Q2. So if an OU entered fine age disags for FY18Q1, they are included in the dataset but are not counted in Pano. So should we include Q1 numbers and be correct or only use Q2 numbers and be consistent?
