### ISSUE TITLE
Partner perf - index testing

### ISSUE THREAD

**Issue by jrose202** [USAID-ICPI/OHA-Tableau-Dashboard-QA-QC#24]
the % are all correct 

however, the total tested for Q1 - FY17 and FY18 are really large and don't agree with Pano.

the values are disproportionate to all other quarters - as if Tableau is adding/multiplying? the Q1 values

see spreadsheet here https://drive.google.com/file/d/1lGjHe_IhQXTeFClct5ra4A4iite9gnWE/view?usp=sharing

**Comment by noahbartlett** [comment]
An issue with combined targets and results for Q1. Fixed.
