### ISSUE TITLE
OU.06: Partner Comparison

### ISSUE THREAD

**Issue by gsarfaty** [USAID-ICPI/OHA-Tableau-Dashboard-QA-QC#26]
Checked against Pano Partner Performance Dashboard for most. PMTCT_EID_Two_Twelve Months and PMTCT_EID_Less_Equal_Two_Months is only in the Age/Sex dashboard which is not disagg by IM.

**Inconsistencies Noted:**
- [x] TB_ART targets by mech are not matching Pano
- [x] TB_STAT results and targets by mech not matching Pano
- [x] TX_TB results and targets by mech not matching Pano
- [x] PMTCT_STAT not matching Pano

**Aesthetic/UI:**
Can remove the following indicators from the dropdown list since they don't have targets against them & therefore no visuals ever show when selected
- [ ] GEND_GBV
- [ ] HRH_PRE
- [ ] TX_NET_NEW

**Indicators checked:**
- [x] HTS_TST
- [x] HTS_TST_NEG
- [x] HTS_TST_POS
- [x] KP_PREV
- [x] OVC_SERV
- [x] OVC_SERV_OVER_18
- [x] OVC_SERV_UNDER_18
- [x] PMTCT_ART
- [x] PMTCT_EID
- [x] PMTCT_EID_Less_Equal_Two_Months
- [x] PMTCT_EID_Two_Twelve_Months
- [x] PMTCT_STAT
- [x] PMTCT_STAT_KnownatEntry_POSITIVE
- [x] PMTCT_STAT_NewlyIdentified_Negative
- [x] PMTCT_STAT_NewlyIdentified_POSITIVE
- [x] PMTCT_STAT_POS
- [x] PP_PREV
- [x] PrEP_NEW
- [x] TB_ART
- [x] TB_STAT
- [x] TX_CURR
- [x] TX_NEW
- [x] TX_TB
- [x] VMMC_CIRC

**Comment by noahbartlett** [comment]
Can you send me a screenshot of the TB indicators?

**Comment by gsarfaty** [comment]
@noahbartlett creating a doc w/screenshots [here](https://docs.google.com/document/d/1B9lfWy8l_y-u3ee3SkC5F351ETNbUzhD8Sg6A5NqU_g/edit).

**Comment by noahbartlett** [comment]
OK. Issues with Pano: 

1) TB_ART: In Pano, targets are using the disaggregate Age Aggregated/Sex (not Total Numerator, like in every other indicator). Results are fine.

2) TB_STAT: In Pano, results are summing up the disaggregates Age Aggregated/Sex and Age Aggregated/Sex/KnownNewPosNeg. Targets are summing up Total numerator and Total denominator. (!)

3) TX_TB appears to be correct.

**Comment by gsarfaty** [comment]
TX_TB appears to be another Pano issue. Partner performance vs. All Mech Analysis shows big discrepancy. Tableau/ @noahbartlett for the win. Should we make a separate ticket to track Pano issues to report via a support ticket? @cnichols3h - because, TB.

I'll probably finish QC using OUxIM MSD instead. No mo' Pano.  :angry:

**Comment by gsarfaty** [comment]
QC against OU x IM

```
library(tidyverse)

install.packages("devtools")
devtools::install_github("ICPI/ICPIutilities")
library(ICPIutilities)


#import data
df_OUxIM <- read_msd("MER_Structured_Dataset_OU_IM_FY17-18_20180622_v2_1.txt")


#add fy18cum
df_OUxIM <- df_OUxIM%>% 
  filter(standardizeddisaggregate == "Total Numerator") %>%
  rename_official() %>% 
  add_cumulative()


#results by agency
df_OUxMech <- df_OUxIM%>% 
  filter(indicator %in% c("HTS_TST", "HTS_TST_NEG", "HTS_TST_POS", "KP_PREV", "OVC_SERV", 
                          "OVC_SERV_OVER_18", 
                          "OVC_SERV_UNDER_18", "PMTCT_ART",
                          "PMTCT_EID","PMTCT_EID_Less_Equal_Two_Months", 
                          "PMTCT_EID_Two_Twelve_Months", 
                          "PMTCT_STAT", "PMTCT_STAT_KnownatEntry_POSITIVE", 
                          "PMTCT_STAT_NewlyIdentified_Negative",
                          "PMTCT_STAT_NewlyIdentified_POSITIVE","PMTCT_STAT_POS", 
                          "PP_PREV", "PrEP_NEW", "TB_ART", 
                          "TB_STAT", "TX_CURR", "TX_NEW", "TX_TB", "VMMC_CIRC")) %>% 
  group_by(operatingunit,fundingagency,implementingmechanismname, indicator) %>% 
  summarise_at(vars(fy2018cum, fy2018_targets), ~ sum(., na.rm = TRUE)) %>% 
  ungroup() %>% 
  mutate(achvmt = round((fy2018cum/fy2018_targets*100),1)) %>% 
  filter(!is.nan(achvmt))

```

**Comment by gsarfaty** [comment]
All discrepancies were issues w/Pano, not Tableau dashboard.
