### ISSUE TITLE
KP.04: TX_NEW

### ISSUE THREAD

**Issue by nmcdavid** [USAID-ICPI/OHA-Tableau-Dashboard-QA-QC#27]
ARP TX_NEW MSM number in Tableau dashboard ≠ Panorama
![image](https://user-images.githubusercontent.com/36705660/42344947-e5e07ebc-806b-11e8-8e88-ddf4dd58563a.png)

@noahbartlett 

[Link](https://drive.google.com/open?id=1nn7FyAtZaBZx7ALAjeVGvIb_U13nkGD3)

**Comment by nmcdavid** [comment]
No FY18 data is available in the dashboard

@noahbartlett

**Comment by noahbartlett** [comment]
That's weird. I have found the same discrepancy but cannot identify the source of the issue.
