### ISSUE TITLE
Partner Performance Workbook - Index Testing Tab

### ISSUE THREAD

**Issue by kgichuhi** [USAID-ICPI/OHA-Tableau-Dashboard-QA-QC#36]
The index testing tab currently examines percent of HTS_POS attributed to index testing by Agency or partner with a scale of achievement focused upon a 30% benchmark.  The problem is the 30% of positives is a goal for the country - not individual partners or agencies.

We therefore need to change this visual and remove the filters.  Recommend:

- Stacked bar chart
- Countries along the x-axis
- Stacked bar to represent HTS_POS, portion that comes from index testing and portion of index testing from USAID for each country 
- Indication of index testing as a percent of positives either with percent shown and icon to indicate where 30% on the bar would be

**Comment by noahbartlett** [comment]
For the purposes of what you are asking, I recommend shifting this visual to the overall dashboard rather than keeping it in the partner performance dashboard. 

I will put something together and share it with the group.

**Comment by kgichuhi** [comment]
Awesome thanks Noah!  We might consider too what Jessica has put together,
given that each country has a different target (few are tasked with the
30%) we would want to look at achievement toward (although unrealistic in
many cases) the target they were handed at RPM and project out what is
needed to reach that rather than the 30%....

K



*Karin Gichuhi, Team Lead, Strategic Information*

USAID Contractor

Bureau of Global Health, Office of HIV/AIDS, SIEI Division

2100 Crystal Drive, #9012A, Arlington, VA  22202

T 571-551-7313  |  M 202-316-4680

Email: kgichuhi@usaid.gov



*GHSI-III - Social Solutions International, Inc. prime contractor*
