### ISSUE TITLE
IM/Partner Swap: LINKAGES

### ISSUE THREAD

**Issue by gsarfaty** [USAID-ICPI/OHA-Tableau-Dashboard-QA-QC#6]
In R code, account for countries that swapped IM and Partner for Linkages. Ex. Angola where LINKAGES is listed as partner instead of Mech. Cross-posted with [issue 14 on One Last Kiss](https://github.com/noahbartlett/Me_One_Last_Kiss/issues/14)

**Comment by noahbartlett** [comment]
Fixed in R code. Now shows as LINKAGES.
