### ISSUE TITLE
Global Tab 01

### ISSUE THREAD

**Issue by kgichuhi** [USAID-ICPI/OHA-Tableau-Dashboard-QA-QC#8]
Global 01: Target Achievement
Need to adjust the performance scale to match that of Panorama and PPR
<25% red, 25-40% yellow, 40-60% green, >60% blue
![image](https://user-images.githubusercontent.com/40864435/42331558-ae480b96-8043-11e8-8a54-9c6a40fe8f5c.png)
![image](https://user-images.githubusercontent.com/40864435/42331598-d01def7e-8043-11e8-9cff-bac07f6892e7.png)

**Comment by noahbartlett** [comment]
Fixed for this version; long term solution still needed. 

When FY19 targets were added, it ruined the clever way I had solved this issue. :(
